@startuml
'https://plantuml.com/class-diagram

class ToDoList {
    +name : String
    +toDoItems : ArrayList<ToDoItem>
    +selected : boolean
    +getName() : String
    +removeItem(ToDoItem item)
    +addItem(ToDoItem Item)
    +displayList(List<ToDoItem> items)
    +completedItems() : List<ToDoItem>
    +incompleteItems() : List<ToDoItem>


}

@enduml